### ISSUE TITLE
Field processing does not handle optional space character

### ISSUE THREAD

**Issue by paulkmoore** [rubinhos/ngx-sse-client#7]
Hi @rubinhos,

Firstly thanks for keeping this library going, I appreciate that maintaining such things takes effort.

I have discovered an issue in [`parseChunkLine`](https://github.com/rubinhos/ngx-sse-client/blob/a5f60e6a240012df1a852852ab4674e50530f8a1/lib/projects/ngx-sse-client/src/lib/sse-client.service.ts#LL142C3-L153C4) which does not handle the optional space character in field lines. For context, please see the [ABNF in the spec](https://html.spec.whatwg.org/multipage/server-sent-events.html#parsing-an-event-stream); specifically:

`field         = 1*name-char [ colon [ space ] *any-char ] end-of-line`

Accordingly, when processing field lines that have the (optional) space character, this ends up being included in the field data i.e. given:

`id: 1234`

the `event.id` field contains `" 1234"`, not `"1234"`.

The spec is specific about this being a single optional space character, but I think in general any leading whitespace should be a candidate to be trimmed; thoughts?

I'm happy to fork and create a PR if that's helpful / appropriate?

Best, Paul

Debugger image for context, please see the rogue space character in the `id` field and `o` variable:

<img width="637" alt="Screenshot 2023-05-10 at 10 13 57" src="https://github.com/rubinhos/ngx-sse-client/assets/611026/2dd97931-5870-4e3a-acd7-6ebdf3b04a16">

**Comment by rubinhos** [comment]
Hey @paulkmoore, how are you doing? I totally agree with you.

Any whitespace should be trimmed. I'll be glad to review your PR, and I will aprove it as soon as possible.

Thank you very much for your contribution!
